## You can change the friendly name if you wish on line 7 below. The friendly name is how the device will show in HA 
## However the <name:> is how HA connects to the device eg. esp32-s3-box-3.local is the mDNS hostname for the device.
## Once added to HA changing the device name can lead to connection issues, between HA and the device.

esphome:
  name: esp32-s3-box-3-5aac68
  friendly_name: ESP32-S3-Box-3

esp32:
  board: esp32s3box
  framework:
    type: esp-idf
    #arduino
#    version: latest # might be required, possibly update esphome version instead

external_components:
  - source: github://rpatel3001/esphome@es7210
    components: [ es7210 ]

globals:
  - id: api_connection
    type: bool
    restore_value: no
    initial_value: "false" 
  - id: wifi_connection
    type: bool
    restore_value: no
    initial_value: "false" 
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
  on_connect:
    - lambda: |-
        id(wifi_connection) = true;
    - component.update: lcd
  on_disconnect:
    - lambda: |-
        id(wifi_connection) = false;
    - component.update: lcd

ota:
  - platform: esphome
api:
  encryption:
    key: !secret esphome_api_key
  on_client_connected:
    - lambda: |-
        id(api_connection) = true;
    - component.update: lcd
  on_client_disconnected:
    - lambda: |-
        id(api_connection) = false;
    - component.update: lcd

interval:
  - interval: 10s
    then:
      - if:
          condition:
            - lambda: 'return { (id(api_connection) != true) };'
          then:
            - if:
                condition:
                  api.connected:
                then:
                  - lambda: "id(api_connection) = true;"
          else:
            - if:
                condition:
                  not:
                    api.connected:
                then:
                  - lambda: "id(api_connection) = false;"

  - interval: 10s
    then:
      - if:
          condition:
            - lambda: 'return { (id(wifi_connection) != true) };'
          then:
            - if:
                condition:
                  wifi.connected:
                then:
                  - lambda: "id(wifi_connection) = true;"
          else:
            - if:
                condition:
                  not:
                    wifi.connected:
                then:
                  - lambda: "id(wifi_connection) = false;"

logger:
  # CDC logging is currently not working on the S3
  # See https://github.com/espressif/esp-idf/commit/9924d9f27192a5fab5f66230c72249ecc6cad34c
  #hardware_uart: USB_CDC
  level: VERBOSE
  logs:
    esp32_ble: WARN
    esp32_ble_tracker: WARN
    ble_dist: WARN
    sensor: WARN
    ledc.output: WARN
    component: WARN
    ili9xxx: WARN
    tt21100: WARN
    touchscreen: WARN
    wifi: WARN
    es8311: WARN
    i2s_audio: VERBOSE
    voice_assistant: VERBOSE
    es7210: WARN

time:
  - platform: homeassistant
    id: time_ha

output:
  - platform: ledc
    pin: GPIO47
    id: backlight_output

light:
  - platform: monochromatic
    id: led
    name: LCD Backlight
    entity_category: config
    output: backlight_output
    restore_mode: ALWAYS_ON
    default_transition_length: 50ms

spi:
  clk_pin: GPIO7
  mosi_pin: GPIO6

display:
  - platform: ili9xxx
    model: S3BOX
    data_rate: 40MHz
    cs_pin: 5
    dc_pin: 4
    #reset_pin:
    #  number: 48
    #  inverted: true
    update_interval: 5s
    id: lcd
    #auto_clear_enabled: false
    invert_colors: false
    # Width = 320, Height = 240
    lambda: |-
      auto bg = Color(250, 250, 250);
      auto text = Color(250, 250, 250);
      auto border_color = Color(60, 60, 60);
      auto button_bg_on = Color(36, 180, 245);
      auto button_bg_off = Color(158, 158, 158);
      auto red = Color(255, 0, 0);
      auto green = Color(0, 255, 0);
      auto blue = Color(0, 0, 255);

      // it.line(0, 0, 50, 50);
      if(id(api_connection) == true) {
        it.printf(15, 5, id(icon_font_55), blue, "\U000F07D0");      
      } else {
        it.printf(15, 5, id(icon_font_55), red, "\U000F087B");
      }

      if(id(wifi_connection) == true) {
        it.printf(80, 5, id(icon_font_55), lime, "\U000F16BD");      
      } else {
        it.printf(80, 5, id(icon_font_55), red, "\U000F16BC");
      }

      it.strftime(160, 65, id(font_large), text, TextAlign::CENTER, "%H:%M", id(time_ha).now());
      it.strftime(160, 115, id(font_medium), text, TextAlign::CENTER, "%a, %b %e", id(time_ha).now());

      int circleY = 187;
      int circleX1 = 53, circleX2 = 160, circleX3 = 267;
      int circleRadius = 40;

      it.filled_circle(circleX1, circleY, circleRadius+2, text);
      it.filled_circle(circleX2, circleY, circleRadius+2, text);
      it.filled_circle(circleX3, circleY, circleRadius+2, text);

      it.printf(30, 20, id(font_small), red, COLOR_OFF, TextAlign::LEFT, "%.0f", id(co2_bedroom).has_state() ? id(co2_bedroom).state : 0);

      if (id(bedroom_light).state){
        it.filled_circle(circleX1, circleY, circleRadius, button_bg_on);
        it.image(circleX1, circleY, id(ceiling_light_icon), ImageAlign::CENTER);
      }
      else{
        it.filled_circle(circleX1, circleY, circleRadius, button_bg_off);
        it.image(circleX1, circleY, id(ceiling_light_icon_off), ImageAlign::CENTER);
      }

      /*if (id(basement_lamps).state){
        it.filled_circle(circleX2, circleY, circleRadius, button_bg_on);
        it.image(circleX2, circleY, id(floor_lamp_icon), ImageAlign::CENTER);
      }
      else{
        it.filled_circle(circleX2, circleY, circleRadius, button_bg_off);
        it.image(circleX2, circleY, id(floor_lamp_icon_off), ImageAlign::CENTER);
      }

      if (id(office_lights).state){
        it.filled_circle(circleX3, circleY, circleRadius, button_bg_on);
        it.image(circleX3, circleY, id(office_icon), ImageAlign::CENTER);
      }
      else{
        it.filled_circle(circleX3, circleY, circleRadius, button_bg_off);
        it.image(circleX3, circleY, id(office_icon), ImageAlign::CENTER);
      }*/

font:
  - file: "gfonts://Roboto@500"
    id: font_large
    size: 70
    glyphs: "0123456789:APM."
  - file: "gfonts://Roboto@500"
    id: font_medium
    size: 30
  - file: "gfonts://Roboto@500"
    id: font_small
    size: 15
  - file: "https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/raw/main/fonts/materialdesignicons-webfont.ttf"
    id: icon_font_55
    size: 30
    glyphs: &icon_glyphs
      - "\U000F0079"#battery 100%
      - "\U000F007A"#battery 10%
      - "\U000F007B"#battery 20%
      - "\U000F007C"#battery 30%
      - "\U000F007D"#battery 40%
      - "\U000F007E"#battery 50%
      - "\U000F007F"#battery 60%
      - "\U000F0080"#battery 70%
      - "\U000F0081"#battery 80%
      - "\U000F0082"#battery 90%
      - "\U000F009E"#bell
      - "\U000F0150"#clock
      - "\U000F01AE"#gbp pound symbol
      - "\U000F0210"#fan
      - "\U000F0238"#heating
      - "\U000F024A"#garden/flower
      - "\U000F0335"#light bulb off
      - "\U000F036C"#microphone on 
      - "\U000F036D"#microphone off 
      - "\U000F036F"#voice settings
      - "\U000F03E4"#pause
      - "\U000F040A"#play
      - "\U000F040E"#play/pause
      - "\U000F0493"#settings cog
      - "\U000F04AD"#next track
      - "\U000F04AE"#previous track
      - "\U000F04B9"#living room
      - "\U000F04C8"#spots
      - "\U000F04DB"#stop
      - "\U000F0502"#screen settings
      - "\U000F050F"#temp sensor
      - "\U000F0521"#toggle on
      - "\U000F0565"#arming
      - "\U000F057E"#speaker on
      - "\U000F0581"#speaker off
      - "\U000F05CB"#voice
      - "\U000F068A"#alarm home
      - "\U000F06E8"#light bulb illuminated
      - "\U000F075A"#music 
      - "\U000F075D"#vol plus
      - "\U000F075E"#vol minus
      - "\U000F0769"#ceiling
      - "\U000F07D0"#api connected
      - "\U000F07F4"#tv
      - "\U000F0873"#car miles non
      - "\U000F0874"#car miles full
      - "\U000F0875"#car miles low
      - "\U000F087B"#api disconnected
      - "\U000F08D6"#settings
      - "\U000F099D"#alarm away
      - "\U000F099E"#disarmed
      - "\U000F0A19"#toggle off
      - "\U000F0B26"#down
      - "\U000F0B28"#left
      - "\U000F0B2A"#right
      - "\U000F0B2C"#up
      - "\U000F0B6C"#car battery
      - "\U000F0D90"#screen off
      - "\U000F0EBA"#stats
      - "\U000F0ED4"#voice off
      - "\U000F0FCE"#scene
      - "\U000F1061"#dining
      - "\U000F10CD"#battery warning
      - "\U000F1160"#kitchen
      - "\U000F12A8"#touch button
      - "\U000F12D3"#garage closed
      - "\U000F12D4"#garage open
      - "\U000F1322"#tools
      - "\U000F16BC"#wifidisconnected
      - "\U000F16BD"#wifi connected
      - "\U000F1722"#fire off
      - "\U000F1747"#tall lamp
      - "\U000F1828"#armed night
      - "\U000F192D"#electricity
      - "\U000F1987"#floods
      - "\U000F1A12"#home button
      - "\U000F1A1B"#gas
      - "\U000F1C3B"#battery charging/usb powered
      - "\U000F1C6F"#info

image:
  - file: mdi:volume-off
    id: mute_icon
    resize: 40x40
  - file: mdi:microphone-off
    id: mic_mute_icon
    resize: 40x40
  - file: mdi:account-voice
    id: voice_icon
    resize: 40x40
  #- file: "esp-s3-box-background.png"
  #  id: background_image
  #  resize: 320x240
  #  type: rgba
  - file: mdi:floor-lamp
    id: floor_lamp_icon
    resize: 40x40
  - file: mdi:floor-lamp-outline
    id: floor_lamp_icon_off
    resize: 40x40
  - file: mdi:ceiling-light
    id: ceiling_light_icon
    resize: 40x40
  - file: mdi:ceiling-light-outline
    id: ceiling_light_icon_off
    resize: 40x40
  - file: mdi:desk
    id: office_icon
    resize: 40x40

i2c:
  - id: bus_a
    sda: GPIO08
    scl: GPIO18
    scan: false
    sda_pullup_enabled: true
    scl_pullup_enabled: true
    frequency: 50kHz



#touchscreen:
#  - platform: tt21100
#    address: 0x24
#    interrupt_pin: GPIO3
    # Don't use as the reset pin is shared with the display, so the ili9xxx will perform the reset
    #reset_pin: GPIO48

touchscreen:
  - platform: gt911
    i2c_id: bus_a
    id: gt911_touchscreen
    interrupt_pin:
      number: GPIO3
      ignore_strapping_warning: true


  
binary_sensor:
  #- platform: gpio
    #pin:
      #number: GPIO0
      #mode: INPUT_PULLUP
      #inverted: true
    #id: side_button
    #name: "Side Button"
    #on_press:
      #- voice_assistant.start:
    #on_release:
      #- voice_assistant.stop:


  #- platform: gpio
    #pin:
      #number: GPIO1
      #inverted: true
    #id: microphone_button
    #name: "Microphone Button"


  - platform: touchscreen
    name: "Bedroom Light"
    x_min: 3
    x_max: 103
    y_min: 137
    y_max: 237
    internal: True
    on_press: 
      then:
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.pw_switch02
        - delay: 200ms
        - component.update: lcd
            
            
  - platform: touchscreen
    name: "Basement Lamps Button"
    x_min: 110
    x_max: 210
    y_min: 137
    y_max: 237
    internal: True
        
  - platform: touchscreen
    name: "Office Lights Button"
    x_min: 216
    x_max: 316
    y_min: 137
    y_max: 237
    internal: True
    
  - platform: homeassistant
    id: bedroom_light
    entity_id: light.pw_switch02

sensor:
  - platform: homeassistant
    id: co2_bedroom
    entity_id: sensor.co2_bedroom
    internal: True
    
color:
  - id: lime
    hex: '20FC30'

#  - platform: homeassistant
#    id: basement_lamps
#    entity_id: light.light_2
#    internal: True

#  - platform: homeassistant
#    id: office_lights
#    entity_id: light.nspanel_relay_1
#    internal: True

#i2s_audio:
#  i2s_lrclk_pin: GPIO47
  #i2s_bclk_pin: GPIO17
  #i2s_mclk_pin: GPIO2

#es8311:
  #address: 0x18

# mutually exclusive with media_player
#speaker:
  #- platform: i2s_audio
    #id: ext_speaker
    #dac_type: external
    #i2s_dout_pin: GPIO15
    #mode: mono

#media_player:
#  - platform: i2s_audio
    #name: Media Player
    #id: ext_speaker
    #dac_type: external
    #i2s_dout_pin: GPIO15
    #mute_pin:
      #number: GPIO46
      #inverted: true

#es7210:
  #address: 0x40

#microphone:
  #- platform: i2s_audio
    #id: ext_mic
    #adc_type: external
    #pdm: false
    #i2s_din_pin: GPIO16
    #bits_per_sample: 16bit

#voice_assistant:
  #id: voice_asst
  #microphone: ext_mic
  #speaker: ext_speaker
  #media_player: ext_speaker

# i2c device at address 0x18 - ES8311 Audio Codec
# i2c device at address 0x24 - TT21100 Touchscreen
# i2c device at address 0x40 - ES7210 Mic ADC
# i2c device at address 0x68 - ICM-42607-P IMU