## You can change the friendly name if you wish on line 7 below. The friendly name is how the device will show in HA 
## However the <name:> is how HA connects to the device eg. esp32-s3-box-3.local is the mDNS hostname for the device.
## Once added to HA changing the device name can lead to connection issues, between HA and the device.


config: !- $import('config.yaml')
substitutions: !? $_.config.substitutions


image: !? $_.page_resources.image
font: !? $_.page_resources.font
color: !? $_.page_resources.color

voice: !- $import('voice.yaml')
#voice_assistant: !? $_.voice.voice_assistant
#micro_wake_word: !? $_.voice.micro_wake_word
#microphone: !? $_.voice.microphone


settings: !- $import('settings.yaml')

hass: !- $import('hass.yaml')


top_layer: !- $import('pages/top_layer.yaml')
page_weather: !- $import('pages/weather.yaml')
page_resources: !- $import('pages/resources.yaml')
page_main: !- $import('pages/main.yaml')
page_settings: !- $import('pages/settings.yaml')
page_wifi_info: !- $import('pages/wifi_info.yaml')


esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.9.0
  platformio_options:
    board_build.psram: "enabled"
    board_build.flash_mode: dio
    build_flags:
      - -D LV_USE_CHART=1  # Enable chart widget, it's not supported by default

  on_boot:
    priority: 600
    then:
      #- lambda: id(led).turn_on().set_brightness(id(s_default_brightness).state /100).perform();
      #- script.execute: saver_enabled
      - lambda: id(time_remaining_0).publish_state ("0:00:00"); 
      # - if:
      #     condition:
      #       switch.is_on: output_audio
      #     then:
      #       media_player.volume_set:    
      #         id: adf_media_player
      #         volume: 0 
  includes:
    - helpers.h

  project:
    name: "dimonb.s3box"
    version: "2025.03.09"

esp32:
  board: esp32s3box
  flash_size: 16MB
  framework:
    type: esp-idf
    #version: 4.4.8
    #platform_version: 5.4.0
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_AUDIO_BOARD_CUSTOM: "y"
      CONFIG_ESP32_S3_BOX_3_BOARD: "y"
      #CONFIG_SPIRAM_USE: y

    # components:
    #   - name: esp32_s3_box_3_board
    #     source: github://jesserockz/esp32-s3-box-3-board@main
    #     refresh: 0s
   
psram:
  mode: octal
  speed: 120MHz
  
http_request:
  useragent: esphome/device
  timeout: 10s
  verify_ssl: false

json:

external_components:
  # - source:
  #     type: git
  #     url: https://github.com/dimonb/esphome_audio
  #     ref: dev-next
  #   components: [ adf_pipeline, i2s_audio ]
  #   refresh: 0s  
  - source:  github://dimonb/esphome@dev
    components: [ http_request]
  - source:  ./external_components
    components: [ json]
    
api:
  encryption:
    key: !secret esphome_api_key
  on_client_connected:
    - lambda: |-
        id(api_connection) = true;
    - !? $_.top_layer.api_status_update.action
    #- lambda: id(led).turn_on().set_brightness(id(s_default_brightness).state /100).perform();
    #- component.update: s3_box_lcd
    #- script.execute: saver_enabled

  on_client_disconnected:
    - lambda: |-
        id(api_connection) = false;
    - !? $_.top_layer.api_status_update.action

ota:
  - !? $import('pages/ota.yaml')
    

logger:
  hardware_uart: USB_SERIAL_JTAG
  level: DEBUG
  logs:
    text_sensor: WARN
    component: ERROR
    auto_brightness: INFO
    main: DEBUG
    weather: DEBUG
    json: DEBUG
    lvgl: DEBUG
    ledc.output: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${name}
    password: s3box123
  on_connect:
    - lambda: |-
        ESP_LOGI("main", "Connected to WiFi");
    - lambda: |-
        id(wifi_connection) = true;
    - !? $_.top_layer.wifi_status_update.action
    - script.execute: weather_update_data
  on_disconnect:
    - lambda: |-
        ESP_LOGI("main", "Disconnected from WiFi");
    - lambda: |-
        id(wifi_connection) = false;
    - !? $_.top_layer.wifi_status_update.action

lvgl:
  displays:
    - s3_box_lcd
  touchscreens:
    - gt911_touchscreen
  top_layer: !? $import('pages/top_layer.yaml')

  pages:
    - !? $_.page_main
    - !? $_.page_settings
    - !? $_.page_wifi_info
    - !? $_.page_weather

  style_definitions: !? $import('pages/styles.yaml')


captive_portal:


time:
  - platform: homeassistant
    id: ha_time
    on_time_sync:
      - lambda: |-
          ESP_LOGI("main", "Time synced %s", id(ha_time).now().strftime("%H:%M").c_str());
      - !? $_.page_main.time_update.action
      - !? $_.page_main.date_update.action
    on_time:
      - minutes: '*'
        seconds: 0
        then:
          - lambda: |-
              ESP_LOGI("main", "Time updated %s", id(ha_time).now().strftime("%H:%M").c_str());
          - !? $_.page_main.time_update.action
          - !? $_.page_main.date_update.action
  

interval:
  - interval: 10s
    then:
      - if:
          condition:
            - lambda: 'return id(api_connection) != api::APIConnectedCondition<>().check();'
          then:
            - lambda: |-
                ESP_LOGE("main", "API connection: %s", id(api_connection) ? "true" : "false");
                id(api_connection) = api::APIConnectedCondition<>().check();
            - !? $_.top_layer.api_status_update.action
          

  - interval: 60s
    then:
      - lambda: |-
          ESP_LOGI("main", "Updating weather");
      - script.execute: weather_update_data

  - interval: 30s
    then:
      - component.update: s3_box_lcd


  - interval: 60s
    then:
      - lambda: |-
          if (id(brightness_auto).state) {
            std::string time_of_day = get_time_of_day();
            int new_brightness = 100;
            // Use local dawn/dusk times for comparison
            if (time_of_day == "day" || time_of_day == "morning") {
              new_brightness = 100;
            } else if (time_of_day == "evening") {
              new_brightness = 65;
            } else {
              new_brightness = 45;
            }

            if (new_brightness != static_cast<int>(id(s_default_brightness).state)) {
              ESP_LOGI("main", "Updating brightness from %d to %d",
                      static_cast<int>(id(s_default_brightness).state), new_brightness);
              id(s_default_brightness).make_call().set_value(new_brightness).perform();
              id(led).turn_on().set_brightness(id(s_default_brightness).state /100).perform();
            }
          }

  

select:
  - platform: template
    entity_category: config
    name: Wake word engine location
    id: wake_word_engine_location
    optimistic: true
    restore_value: true
    options:
      - In Home Assistant
      - On device
    initial_option: In Home Assistant
    on_value:
      - if:
          condition:
            lambda: return x == "In Home Assistant";
          then:
            #- micro_wake_word.stop
            - delay: 500ms
            #- lambda: id(va).set_use_wake_word(true);
            #- voice_assistant.start_continuous
            - text_sensor.template.publish:
                id: wakeword_location
                state: !lambda 'return "Home Assistant";'
            - component.update: s3_box_lcd
      - if:
          condition:
            lambda: return x == "On device";
          then:
            - text_sensor.template.publish:
                id: wakeword_location
                state: !lambda 'return "On Device";'
            #- lambda: id(va).set_use_wake_word(false);
            #- voice_assistant.stop
            - delay: 500ms
            #- micro_wake_word.start
            - component.update: s3_box_lcd

  - platform: template
    entity_category: config
    name: Time Format
    id: time_format
    optimistic: true
    restore_value: true
    options:
      - 12 Hr
      - 24 Hr
    initial_option: 24 Hr
    on_value:
      then:
        - if:
            condition:
              lambda: return x == "24 Hr";
            then:
              - text_sensor.template.publish:
                  id: time_display_format
                  state: !lambda 'return "24 Hr";'
            else:
              - text_sensor.template.publish:
                    id: time_display_format
                    state: !lambda 'return "12 Hr";'
        - component.update: s3_box_lcd
                
script:   
  - !for $_.settings.script: !()
    - !? $

  - !for $_.page_weather.script: !()
    - !? $

  - id: set_volume
    then:
      - lambda: |-
          ESP_LOGI("main", "Setting volume to"); //, id(speaker_volume).state);
      # - media_player.volume_set:
      #     volume: !lambda return 0.5 + id(speaker_volume) * 0.05 ;
          
  - id: timer_started
    then:      
      - lambda: |-
          ESP_LOGI("main", "Timer started");
      # while:
      #   condition:
      #     switch.is_on: timer_ringing
      #   then:    
      #     - media_player.play_media:
      #         media_url: '${home_assistant_host}/local/sounds/timer_finished.mp3'
      #     - delay: 1s   
        
  - id: timer_started_external
    then:
      while:
        condition:
          switch.is_on: timer_ringing
        then:
          - homeassistant.service:
              service: media_player.play_media
              data:
                entity_id: media_player.${external_media_player}
                media_content_id: '${home_assistant_host}/local/sounds/timer_finished.mp3'
                media_content_type: music
          - delay: 1700ms
        
        
  # - id: timer_ending
  #   then:
  #     - wait_until: 
  #           - lambda: return (id(time_remaining_0).state == "0:00:10");
  #     - script.execute: saver_enabled
  #     - display.page.show: time_remaining_page
  #     - component.update: s3_box_lcd         

 
globals:
  - id: manual_render
    type: bool
    initial_value: 'false'
  - id: wifi_connection
    type: bool
    restore_value: no
    initial_value: "false"
  - id: api_connection
    type: bool
    restore_value: no
    initial_value: "false" 
  - id: mute_value
    type: bool
    restore_value: no
    initial_value: "false" 
  - id: speaker_volume
    type: int
    restore_value: no
    initial_value: '5'
  - id: media_state
    type: bool
    restore_value: no
    initial_value: "false"
  # - id: global_first_active_timer
  #   type: voice_assistant::Timer
  #   restore_value: false
  - id: global_is_timer_active
    type: bool
    restore_value: false
  # - id: global_first_timer
  #   type: voice_assistant::Timer
  #   restore_value: false
  - id: global_is_timer
    type: bool
    restore_value: false    
  - id: current_pin
    type: std::string
    initial_value: "" 

number:
  - !for $_.settings.number: !()
    - !? $


button:
  - platform: restart
    id: reboot
    name: "Reboot"
    entity_category: diagnostic
    
switch:
  - !for $_.settings.switch: !()
    - !? $
 
output:
  - platform: ledc
    pin: GPIO47
    id: backlight_output

light:
  - platform: monochromatic
    id: led
    name: LCD Backlight
    entity_category: config
    output: backlight_output
    restore_mode: ALWAYS_ON
    default_transition_length: 50ms
    
sensor:         
  - platform: uptime
    id: up_sens
    on_value:
      - lambda: |-
          int seconds = id(up_sens).state;
          int days = seconds / 86400;
          int hours = seconds / 3600;
          int minutes = (seconds % 3600) / 60;
          seconds %= 60;
          id(up_sens_text).publish_state(str_sprintf("%03d:%02d:%02d:%02d", days, hours, minutes, seconds)); 
    update_interval: 30s

  - platform: wifi_signal
    name: "WiFi db"
    id: wifi_signal_db
    update_interval: 30s

    
  - platform: copy 
    source_id: wifi_signal_db
    name: "WiFi Signal"
    id: wifi_percent
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""   
    on_value:
      - lvgl.label.update:
          id: wifi_percent_label
          text: !lambda return str_sprintf("%4.f%%", id(wifi_percent).state);
    
  - !for $_.hass.sensor: !()
    - !? $

text_sensor:
  - id: text_request
    platform: template
    on_value:
      lambda: |-
        if(id(text_request).state.length()>32) {
          std::string name = id(text_request).state.c_str();
          std::string truncated = esphome::str_truncate(name.c_str(),31);
          id(text_request).state = (truncated+"...").c_str();
        }

  - id: text_response
    platform: template
    on_value:
      lambda: |-
        if(id(text_response).state.length()>32) {
          std::string name = id(text_response).state.c_str();
          std::string truncated = esphome::str_truncate(name.c_str(),31);
          id(text_response).state = (truncated+"...").c_str();
        }
  - platform: wifi_info
    ip_address:
      name: IP Address
      id: ip_addr
      entity_category: "diagnostic"
    ssid:
      id: connected_ssid
      name: SSID
      entity_category: "diagnostic"
      on_value:
        - lvgl.label.update:
            id: connected_ssid_label
            text: !lambda return id(connected_ssid).state.c_str();
    bssid:
      id: connected_bssid
      name: BSSID
      entity_category: "diagnostic"
      on_value:
        - lvgl.label.update:
            id: connected_bssid_label
            text: !lambda return id(connected_bssid).state.c_str();
    mac_address:
      id: device_mac
      on_value:
        - lvgl.label.update:
            id: device_mac_label
            text: !lambda return id(device_mac).state.c_str();

  - platform: template
    id: up_sens_text
    name: Device uptime
    entity_category: "diagnostic"
    icon: mdi:clock

  - platform: template
    id: wakeword_location

  - platform: template
    id: time_remaining_0
    name: Timer 
    icon: mdi:clock
               
  - platform: template
    id: time_remaining_1

  - platform: template
    id: time_display_format
    update_interval: never

  - platform: homeassistant
    entity_id: media_player.${external_media_player}
    id: ha_media_status
    on_value:
      component.update: s3_box_lcd

  - platform: homeassistant
    entity_id: media_player.${external_media_player}
    id: ha_media_title
    attribute: media_content_id
    on_value:
      component.update: s3_box_lcd 

  - platform: homeassistant
    name: "Alarm Status"
    entity_id: alarm_control_panel.alarmo
    id: alarm_status  
    on_value:
      - component.update: s3_box_lcd    

  - !for $_.hass.text_sensor: !()
    - !? $
      
# i2s_audio:
#   - id: i2s_shared
#     i2s_lrclk_pin:
#       number: GPIO45
#       ignore_strapping_warning: true
#     i2s_bclk_pin: GPIO17
#     i2s_mclk_pin: GPIO2
#     access_mode: duplex

# adf_pipeline:
#   - platform: i2s_audio
#     type: audio_out
#     id: adf_i2s_out
#     i2s_audio_id: i2s_shared
#     i2s_dout_pin: GPIO15
#     adf_alc: false
#     dac:
#       i2c_id: bus_a
#       model: es8311
#       address: 0x18
#       enable_pin:
#         number: GPIO46
#         ignore_strapping_warning: true
#     sample_rate: 16000
#     bits_per_sample: 16bit
#     fixed_settings: true

#   - platform: i2s_audio
#     type: audio_in
#     id: adf_i2s_in
#     i2s_audio_id: i2s_shared
#     i2s_din_pin: GPIO16
#     pdm: false
#     adc:
#       i2c_id: bus_a
#       model: es7210
#       address: 0x40
#     sample_rate: 16000
#     bits_per_sample: 16bit
#     fixed_settings: true

# media_player:
#   - platform: adf_pipeline
#     id: adf_media_player
#     name: s3-box_media_player
#     internal: false
#     keep_pipeline_alive: true
#     announcement_audio:
#       sample_rate: ${tts_voice_speed}
#       bits_per_sample: 16
#       num_channels: 1
#     pipeline:
#       - self
#       - resampler
#       - adf_i2s_out
#     on_play: 
#       - lambda: |-
#           id(media_state) = true;
#       - component.update: s3_box_lcd
#     on_idle:
#       - lambda: |-
#           id(media_state) = false;
#       - component.update: s3_box_lcd


spi:
  clk_pin: 7
  mosi_pin: 6


display:
  - platform: ili9xxx
    id: s3_box_lcd
    model: S3BOX
    data_rate: 40MHz
    cs_pin: 5
    dc_pin: 4
    reset_pin:
      number: 48
      inverted: true
    update_interval: never
    invert_colors: false
    auto_clear_enabled: false

i2c:
  - id: bus_a
    sda: GPIO08
    scl: GPIO18
    scan: false
    sda_pullup_enabled: true
    scl_pullup_enabled: true
    frequency: 100kHz

  - sda: GPIO41
    scl: GPIO40
    scan: false
    sda_pullup_enabled: true
    scl_pullup_enabled: true
    frequency: 50kHz
    id: bus_b


touchscreen:
  - platform: gt911
    i2c_id: bus_a
    id: gt911_touchscreen
    interrupt_pin:
      number: GPIO3
      ignore_strapping_warning: true
    on_touch:
      - lambda: |-
          id(led).turn_on().set_brightness(id(s_default_brightness).state /100).perform();
          ESP_LOGD("gt911_touchscreen", "Touch at x=%i, y=%i", touch.x, touch.y);
    on_release:
      - script.execute: saver_enabled 
   


binary_sensor:
###### top left hand physical button #######
  - platform: gpio
    id: top_left_button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
      ignore_strapping_warning: true
    on_press:
      - lvgl.page.show: page_main
      # - if:
      #     condition:
      #       - display.is_displaying_page: saver_page
      #     then:
      #       - lambda: id(led).turn_on().set_brightness(id(s_default_brightness).state /100).perform();
      #       - display.page.show: idle_page
      #       - script.execute: saver_enabled
      #       - component.update: s3_box_lcd
      #     else:
      #       if:
      #         condition:
      #           - display.is_displaying_page: idle_page
      #         then:
      #           - script.execute: saver_enabled
      #           - display.page.show: saver_page
      #           - component.update: s3_box_lcd
            
# #######     red circle home button   #####################
  - platform: gt911
    id: home_button
    index: 0
    on_press:
      - lvgl.page.show: page_main
      # if:
      #   condition:
      #     - display.is_displaying_page: idle_page  
      #   then:
      #     - script.execute: saver_enabled
      #   else: 
      #     - lambda: id(led).turn_on().set_brightness(id(s_default_brightness).state /100).perform();
      #     - display.page.show: idle_page
      #     - component.update: s3_box_lcd

  - !for $_.hass.binary_sensor: !()
    - !? $

  