text_sensor:
  - platform: homeassistant
    name: "Weather Condition"
    entity_id: sensor.openweathermap_condition
    id: openweathermap_condition
    on_value:
      - component.update: s3_box_lcd
      
  - platform: homeassistant
    name: "Sun next dawn"
    entity_id: sensor.sun_next_dawn
    id: sun_next_dawn

  - platform: homeassistant
    name: "Sun next dusk"
    entity_id: sensor.sun_next_dusk
    id: sun_next_dusk

  - platform: homeassistant
    id: ims_forecast_today
    name: "IMS Forecast Today"
    entity_id: sensor.ims_forecast_today_json
    on_value:
      - lambda: |
          ESP_LOGD("ims_forecast_today", "IMS Forecast Today: %s", id(ims_forecast_today).state.c_str());
      - component.update: s3_box_lcd

  - platform: homeassistant
    id: ims_forecast_day1
    name: "IMS Forecast Day 1"
    entity_id: sensor.ims_forecast_day1
    attribute: description
    on_value:
      - lambda: |
          ESP_LOGD("ims_forecast_day1", "IMS Forecast Day 1: %s", id(ims_forecast_day1).state.c_str());
      - component.update: s3_box_lcd

sensor:
  - platform: homeassistant
    id: openweathermap_temperature
    entity_id: sensor.openweathermap_temperature
    internal: True
    on_value:
      component.update: s3_box_lcd

  - platform: homeassistant
    id: co2_bedroom
    entity_id: sensor.co2_bedroom
    internal: True
    on_value:
      - lvgl.label.update:
          id: co2_bedroom_status
          text: !lambda return str_sprintf("%4.0f", id(co2_bedroom).state);
          text_color: !lambda return co2_color(id(co2_bedroom).state);
      - lvgl.label.update:
          id: co2_bedroom_icon
          text_color: !lambda return co2_color(id(co2_bedroom).state);
      - component.update: s3_box_lcd


  - platform: homeassistant
    id: temperature_bedroom
    entity_id: sensor.sensor_temp02_temperature
    internal: True
    on_value:
      - lvgl.label.update:
          id: temp_bedroom_status
          text: 
            format: "%2.1f°"
            args: [id(temperature_bedroom).state]
          
      - component.update: s3_box_lcd


  # - !for list(0, 1, 2, 3, 4): !()
  #     - platform: homeassistant
  #       id: !? '"temperature_forecast_max_day_" + str($)'
  #       entity_id: !? '"sensor.home_assistant_realfeel_temperature_max_day_" + str($)'
  #       internal: True
  #       on_value:
  #         component.update: s3_box_lcd
  #     - platform: homeassistant
  #       id: !? '"temperature_forecast_min_day_" + str($)'
  #       entity_id: !? '"sensor.home_assistant_realfeel_temperature_min_day_" + str($)'
  #       internal: True
  #       on_value:
  #         component.update: s3_box_lcd
  #     - platform: homeassistant
  #       id: !? '"condition_forecast_day_" + str($)'
  #       entity_id: !? '"sensor.home_assistant_condition_day_" + str($)'
  #       internal: True
  #       on_value:
  #         component.update: s3_box_lcd

binary_sensor:
  - platform: homeassistant
    id: bedroom_light
    entity_id: light.pw_switch02

