[wokwi]
version = 1
elf = ".esphome/test/.esphome/build/test-esp32-device/.pioenvs/test-esp32-device/firmware.elf"
firmware = ".esphome/test/.esphome/build/test-esp32-device/.pioenvs/test-esp32-device/firmware.bin"

[[net.forward]]
from = "localhost:8180"
to = "target:80"